@startuml User Delete interview (DELETE)
title "User Delete interview (DELETE)"

participant "Client" as user
participant "<<javaScript>>\n:server" as server
participant "<<router>>\n:interviews" as router
participant "<<middleware>>\n:auth" as auth
participant "<<controllers>>\n:interviews" as controller
participant "<<models>>\n:Interview" as model
database "<<MongoDB>>\n:Interviews" as database

user->server ++:req.post('/interview/:id')
server->router ++:app.use('/interviews',interviews)
router->auth ++:protect()
auth --> router --: next()
router -> controller ++:deleteInterview()
controller->model ++:findByIdAndDelete(req.params.id)
model ->database ++: InterviewSchema
database --> model --: interview
controller <-- model --: interview
controller -> user --:response
@enduml
